name: weather_app
description: "Weather App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_staggered_animations: ^1.1.1
  dio_http2_adapter: ^2.5.2
  http_requests: ^3.2.0
  intl: ^0.19.0
  geolocator: ^12.0.0
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  hive: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/logo/
    - assets/icons/


flutter_icons:
  image_path: "assets/logo/logo.jpg"
  adaptive_icon_background: "#ffffff"
  android: true
  ios: true


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/transparent logo.png
  color_dark: "#121212"
  image_dark: assets/logo/transparent logo.png

  android_12:
    image: assets/logo/transparent logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/logo/transparent logo.png
    icon_background_color_dark: "#121212"